categories/urls.py
from django.conf.urls import url

from .views import (
    CategoryListView,
    CategoryDetailView,
    )

urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', CategoryDetailView.as_view(), name='detail')
]

mpi_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView
from profiles.views import(login_view, register_view, logout_view)

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^courses/', include('courses.urls', namespace='courses')),

    # login, register, logout
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.conf.urls import url


from .views import (
        SearchView
    )

urlpatterns = [
    url(r'^$', SearchView.as_view(), name='default'),
]

categories/models.py
from django.core.urlresolvers import reverse
from django.db import models
from videos.models import Video


class CategoryQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)


class CategoryManager(models.Manager):
    # Переопределение queryset
    def get_queryset(self):
        return CategoryQuerySet(self.model, using=self._db)
    
    # category.objects.all не будет возвращать неактивные курсы
    def all(self):
        return self.get_queryset().all().active() #changed

class Category(models.Model):
    title           = models.CharField(max_length=60, verbose_name='SEO заголовок (до 60 симв)')
    seodesc         = models.CharField(max_length=160, verbose_name='SEO описание(до 160)')
    seokw           = models.CharField(max_length=160, verbose_name='SEO Ключевые слова')
    video           = models.OneToOneField(Video, null=True, blank=True, verbose_name='Видео')
    slug            = models.SlugField(unique=True, verbose_name='Ссылка')
    description     = models.TextField(verbose_name='Описание')
    active          = models.BooleanField(default=True, verbose_name='Отображается')
    updated         = models.DateTimeField(auto_now=True, verbose_name='Обновлено:')
    timestamp       = models.DateTimeField(auto_now_add=True, verbose_name='Создано:')
    
    objects = CategoryManager()
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        
    # Вычисление абсолютного URL для выбранного курса
    def get_absolute_url(self):
        return reverse("categories:detail", kwargs={"slug": self.slug})
    # Возвращает название курса (title) при его печати
    def __str__(self):
        return self.title

categories/forms.py
from django import forms
from videos.models import Video
from .models import Category


class CategoryAdminForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'title',
            'slug',
            'seodesc',
            'seokw',
            'video',
            'description',
            'active',
        ]

    # Для видео доступны только неиспользованные видео или уже выбранное заранее видео 
    def __init__(self, *args, **kwargs):
        super(CategoryAdminForm, self).__init__(*args, **kwargs)
        obj = kwargs.get("instance")
        qs = Video.objects.all().unused()
        if obj:
            if obj.video:
                this_ = Video.objects.filter(pk=obj.video.pk)
                qs = (qs | this_)
            self.fields['video'].queryset = qs
        else:
            self.fields['video'].queryset = qs

categories/views.py
from django.views.generic import (
        DetailView,
        ListView,
    )

from .models import Category


class CategoryDetailView(DetailView):
    queryset = Category.objects.all()


class CategoryListView(ListView):
    # QS из всех активных курсов отсортированных по заголовку
    queryset = Category.objects.all().order_by('title')

search/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View

from categories.models import Category
from courses.models import Course, Lecture


class SearchView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        # Стандартное состояние
        course_qs = None
        cat_qs = None
        lec_qs = None
        # Если выполняется поиск по сайту
        if query:
            # Искать в заголовке или описании
            search = Q(title__icontains=query) \
                         | Q(description__icontains=query)
            # Проверка наличия соответствий
            course_qs = Course.objects.filter(search).distinct()
            cat_qs = Category.objects.filter(search).distinct()
            lec_qs = Lecture.objects.filter(search).distinct()

        context = {"course_qs": course_qs, "cat_qs": cat_qs, "lec_qs": lec_qs}
        return render(request, "search/default.html", context)

search/templates/search/snippets/category.html
<a href='{{ item.get_absolute_url }}' class="list-group-item">{{ item.title }}
{% if item.courses_length > 0 %}
    <span class="badge">{{ item.courses_length }} Course{% if courses_length > 1 %}s{% endif %}</span>
{% endif %}

{% if item.category.all.exists %}
    <span class="badge">{{ item.category.all.count }}</span>
{% endif %}
</a>

search/templates/search/snippets/courses.html
<div class="row">
<div class='col-md-4 col-sm-12'>
<div class="thumbnail">
{% if course.image %}
  <a href="{{ course.get_absolute_url }}"><img src="{{ course.image.url }}" class='img-responsive'></a>
{% endif %}
  <div class="caption">
    <h3>{{ course.title }}</h3>
    {% if course.description %}<p>{{ course.description|truncatechars:100 }}</p>{% endif %}
    <p><a href="{{ course.get_absolute_url }}" class="btn btn-primary" role="button">Подробнее</a></p>

  </div>
</div>
</div>
</div>

search/templates/search/snippets/search_form.html
{% if not navbar %}
<form method='GET' action='{% url "search:default" %}'>
<input type='text' value='{{ request.GET.q }}' name='q' required class='form-control' placeholder="Найти..">
<!-- <input type='hidden' value='{{ request.GET.page }}' name='page' class='form-control'> -->
<button  class='btn btn-default' type='submit' ><i class='fa fa-search'></i> Поиск</button>
</form>

{% else %}
<form class="navbar-form navbar-left" method='GET' action='{% url "search:default" %}'>
<div class="form-group">
  <input type='text' value='{{ request.GET.q }}' name='q' required class='form-control' placeholder="Найти..">
</div>
<button  class='btn btn-default' type='submit' ><i class='fa fa-search'></i> Поиск</button>
</form>
{% endif %}