courses/urls.py
from django.conf.urls import include, url


from .views import (
    CourseListView, 
    CourseDetailView, 
    LectureDetailView,
    CoursePurchaseView,
    OwnedView,
    )

urlpatterns = [
    url(r'^$', CourseListView.as_view(), name='list'),
    url(r'^owned/$', OwnedView.as_view(), name='owned'),
    url(r'^(?P<slug>[\w-]+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/purchase/$', CoursePurchaseView.as_view(), name='purchase'),
    url(r'^(?P<cslug>[\w-]+)/(?P<lslug>[\w-]+)/$', LectureDetailView.as_view(), name='lecture-detail'),

]

mpi_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView
from profiles.views import(login_view, register_view, logout_view)

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^courses/', include('courses.urls', namespace='courses')),

    # login, register, logout
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Курсы</h1>
   <div class='row'>
    {% for item in qs %}
        <div class='col-sm-4'>
        {% include 'courses/snippets/course_thumbnail_display.html' with course=item %}
        </div>
        {% cycle '' '' '</div><div class="row">' %}
    {% endfor %}
    </div>


{% endblock content %}

templates/layout.html
{% load search_form %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="{% block seodesc %}{% endblock seodesc %}" />
<meta name="keywords" content="{% block seokw %}{% endblock seokw %}">
<title>{% block title %}{% endblock title %}</title>


<meta name="DC.type" content="{% block DCtype %}interactive resource{% endblock DCtype %}" />
<meta name="DC.identifier" content="{% block url %}{% endblock %}" />
<meta name="DC.language" content="ru-RU"/>
<meta name="DC.coverage" content="Russia" />
<meta name="DC.rights" content="online-mpi all right reserved" />
<!--Open Graph-->
<meta property="og:image" content="{% block imgurl %}{% endblock %}">
<meta property="og:type" content="{% block OGtype %}{% endblock OGtype %}"/>

    {% include 'defaults/head.html' %}
  </head>
  <body>
    
    <div class='container'>
    {% include 'navbar.html' %}
      {% block content %}
      {% endblock content %}
    </div>

    
   {% include 'defaults/scripts.html' %}

  </body>
</html>

templates/navbar.html
{% load search_form %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">online-mpi</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      {% search_form request True %}

    
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'courses:list' %}">Курсы</a></li>
        <li><a href="{% url 'categories:list' %}">Категории</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'login' %}">Войти</a></li>
        <li><a href="{% url 'register' %}">Регистрация</a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <li><a href="{% url 'courses:owned' %}">Купленные курсы</a></li>    
        <li><a href="{% url 'logout' %}">Выход</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>